### ISSUE TITLE
Navigáció, szenzorok, ablakok

### ISSUE THREAD

**Issue by robertfiko** [JNSchwartz/reqengcrew_marsrover#10]
Együtt lehet/kell dolgozni valamennyire: #9 #2

**Comment by szeredniklaszlo** [comment]
Navigáció:
 - helyzetmeghatározás: űrbázis marsi műholdjaira csatlakozás moduláris antennák segítségével
 - térkép felépítése: műholddal készült felvételekkel, marsjáró által már bejárt helyekről készült adatrögzítés által
 - környezetfelmérés közelségérzékelőkkel, nagy felbontású és mélységérzékelő kamerákkal (ezek által biztosítva a zavartalan meghajtást)

Szenzorok:
 - moduláris
 - külső szenzorok: időjárást (hőmérséklet, légnyomás) és napállást jelző szenzor (hogy mérni tudjuk, alkalmasak-e a körülmények a marsjáró számára)
 - belső szenzorok: marsjáró és szkafanderek töltöttség-mérése, oxigénszint-mérő, nyomásszint-mérő, hőmérő (ezáltal ellenőrizve a megrendelő által elvárt belső hőt), kőzetminták tömegének mérése (hogy ne lépjük túl a megrendelő által maximálisan elvártan szállított kőzetek tömegét)
 - különleges policy (kevés üzemanyag) energiahasználatot érintve: nem szükséges szenzorok kikapcsolása, ezzel hosszabb utak biztosítása

Ablakok:
 - a legstrapabíróbb üveg UV réteggel, karc és törésálló

Összes szerkezet és eszköz:
 - gyártása és/vagy beszerzése
 - az azokhoz szükséges alapanyagok beszerzése
 - aki végzi a gyártást / kitől szerezzük be az alapanyagot / eszközt (alvállalkozók / beszállítók)

**Comment by robertfiko** [comment]
Merged in #4
